name: Feature Request
description: Suggest a new feature or improvement for the Fashion app.
labels:
  - "enhancement"
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: >
        A clear and concise description of what the problem is.  
        Example: "I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: >
        Provide a detailed explanation of how this feature should work.  
        If applicable, mention how it integrates with Django or React.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: >
        List any alternative solutions or workarounds you've tried or considered.
  - type: dropdown
    attributes:
      label: Which Django features or services does this feature involve?
      description: Select the Django features or services related to this feature.
      multiple: true
      options:
        - Django REST Framework (DRF)
        - Django Authentication
        - Django ORM (Database Models)
        - Django Celery (Task Queue)
        - Django Channels (WebSockets)
        - Other (Specify in Additional Context)
  - type: dropdown
    attributes:
      label: Which React features does this feature involve?
      description: Select the React features or libraries related to this feature.
      multiple: true
      options:
        - React Router
        - Redux
        - Context API
        - React Hooks
        - Axios / Fetch (for API calls)
        - Other (Specify in Additional Context)
  - type: input
    attributes:
      label: Platform
      description: Specify whether this is for Web, or if you have specific platform considerations (e.g., mobile web, desktop).
      placeholder: "e.g., Web"
  - type: dropdown
    attributes:
      label: Would you like to work on this issue?
      description: Select whether you would like to work on this issue
      multiple: false
      options:
        - 'Yes'
        - 'No'
  - type: textarea
    attributes:
      label: Additional Context
      description: >
        Add any other relevant details, mockups, or screenshots to support your request.
